# Generated by Django 5.2.5 on 2026-07-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
