# Generated by Django 5.2.5 on 2026-07-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_report_type_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
